### ISSUE TITLE
Failed to resolve plugin for module "react-native-auth0" relative to "/home/runner/work/app-rn/app-rn" on Github Actions

### ISSUE THREAD

**Issue by RamboGj** [auth0/react-native-auth0#876]
### Checklist

- [X] The issue can be reproduced in the [react-native-auth0 sample app](https://github.com/auth0-samples/auth0-react-native-sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When building my react native app locally using eas build (VSCode) I can execute it and the deploy works well. But , when I try to do the same using Github Actions, my action fails.

It fails on the step *Build*

```
Run eas build --platform android --profile closed --non-interactive --no-wait
  
Loaded "env" configuration for the "closed" profile: no environment variables specified. Learn more: https://docs.expo.dev/build-reference/variables/
Failed to resolve plugin for module "react-native-auth0" relative to "/home/runner/work/app-rn/app-rn"
    Error: build command failed.
Error: Process completed with exit code 1.
```

### Reproduction

Just copy my CI/CD pipelane and run it on a project that has react-native-auth0

### Additional context

My CI/CD
```
name: CI/CD

on: 
  push:
    branches:
      - main 

jobs: 
  CI: 
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      # - name: Run Tests **** TO ADD
      #   run: npm test
  CD:
    name: Continuous Delivery
    runs-on: ubuntu-latest

    needs: CI

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with: 
          node-version: 20.x

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          packager: npm
          token: ${{ secrets.EAS_EXPO_TOKEN }}

      - name: Build
        run: eas build --platform android --profile closed --non-interactive --no-wait
        ```

### react-native-auth0 version

3.1.0

### React Native version

0.72.6

### Expo version

49.0.18

### Platform

Android

### Platform version(s)

API 33
